"""criacao das tabelas conta categoria transacao alerta

Revision ID: 0c68856f9520
Revises: 
Create Date: 2026-09-08 02:00:23.060636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c68856f9520'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('conta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('saldo_atual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('recomendacao', sa.Text(), nullable=True),
    sa.Column('data', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('nivel_risco', sa.String(length=10), nullable=True),
    sa.CheckConstraint("nivel_risco IN ('baixo', 'medio', 'alto')", name='ck_alerta_nivel_risco_valido'),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerta', schema=None) as batch_op:
        batch_op.create_index('idx_alerta_conta_id', ['conta_id'], unique=False)

    op.create_table('transacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.CheckConstraint("tipo IN ('entrada', 'saida')", name='ck_transacao_tipo_valido'),
    sa.CheckConstraint('valor > 0', name='ck_transacao_valor_positivo'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.create_index('idx_transacao_conta_id', ['conta_id'], unique=False)
        batch_op.create_index('idx_transacao_data', ['data'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.drop_index('idx_transacao_data')
        batch_op.drop_index('idx_transacao_conta_id')

    op.drop_table('transacao')
    with op.batch_alter_table('alerta', schema=None) as batch_op:
        batch_op.drop_index('idx_alerta_conta_id')

    op.drop_table('alerta')
    op.drop_table('conta')
    op.drop_table('categoria')
    # ### end Alembic commands ###
